### ISSUE TITLE
Video je na serveru který není podporován

### ISSUE THREAD

**Issue by nenadalm** [kodi-czsk/plugin.video.sledujuserialy.cz#1]
https://github.com/lzoubek/xbmc-doplnky/issues/284

**Comment by lubo** [comment]
Tato chyba sa netyka konkretneho pluginu, ale stream resolveru. Stream resolver dany server bud nepodporuje alebo ide o bug. Prosim, vytvor novu issue v [kodi-czsk/script.module.stream.resolver](/kodi-czsk/script.module.stream.resolver) a napis, ze aky server ti nefunguje.
